application: focused-zephyr-717
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /scores_api/
  script: mktmaking.application

- url: /
  script: mktmaking.application

- url: /login\.html
  script: mktmaking.application

- url: /index\.html
  script: mktmaking.application

- url: /is_logged_api
  script: mktmaking.application

- url: .*
  script: mktmaking.application
  login: required

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

- name: django
  version: latest